"""Authentication middleware — supports API keys, LDAP, and OIDC."""

from __future__ import annotations

import json
import logging
import secrets
from datetime import UTC, datetime, timedelta
from uuid import uuid4

import bcrypt
import jwt
from fastapi import Depends, HTTPException, Request
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from lean_ai_serve.config import get_settings
from lean_ai_serve.db import Database
from lean_ai_serve.models.schemas import AuthUser

logger = logging.getLogger(__name__)

_bearer_scheme = HTTPBearer(auto_error=False)

# Prefix for API keys generated by this system
API_KEY_PREFIX = "las-"

# In-memory set of revoked JWT IDs — loaded at startup, updated on logout/refresh
_revoked_tokens: set[str] = set()


async def load_revoked_tokens(db: Database) -> None:
    """Load non-expired revoked tokens from DB into memory. Called at startup."""
    now = datetime.now(UTC).isoformat()
    rows = await db.fetchall(
        "SELECT jti FROM revoked_tokens WHERE expires_at > ?", (now,)
    )
    _revoked_tokens.clear()
    for row in rows:
        _revoked_tokens.add(row["jti"])
    logger.info("Loaded %d revoked tokens into memory", len(_revoked_tokens))


async def revoke_token(db: Database, jti: str, user_id: str, expires_at: str) -> None:
    """Revoke a JWT by adding its jti to the revocation store."""
    _revoked_tokens.add(jti)
    await db.execute(
        "INSERT OR IGNORE INTO revoked_tokens (jti, user_id, revoked_at, expires_at) "
        "VALUES (?, ?, ?, ?)",
        (jti, user_id, datetime.now(UTC).isoformat(), expires_at),
    )
    await db.commit()


async def cleanup_revoked_tokens(db: Database) -> int:
    """Remove expired entries from the revocation table and memory."""
    now = datetime.now(UTC).isoformat()
    rows = await db.fetchall(
        "SELECT jti FROM revoked_tokens WHERE expires_at <= ?", (now,)
    )
    expired_jtis = {row["jti"] for row in rows}
    _revoked_tokens.difference_update(expired_jtis)
    result = await db.execute("DELETE FROM revoked_tokens WHERE expires_at <= ?", (now,))
    await db.commit()
    return result.rowcount


# ---------------------------------------------------------------------------
# API Key management
# ---------------------------------------------------------------------------


def generate_api_key() -> str:
    """Generate a new API key with the las- prefix."""
    return f"{API_KEY_PREFIX}{secrets.token_urlsafe(32)}"


def hash_api_key(key: str) -> str:
    """Bcrypt hash an API key for storage."""
    return bcrypt.hashpw(key.encode(), bcrypt.gensalt()).decode()


def verify_api_key(key: str, key_hash: str) -> bool:
    """Verify an API key against its bcrypt hash."""
    return bcrypt.checkpw(key.encode(), key_hash.encode())


async def create_api_key(
    db: Database,
    *,
    name: str,
    role: str = "user",
    models: list[str] | None = None,
    rate_limit: int = 0,
    expires_days: int | None = None,
) -> tuple[str, str]:
    """Create a new API key. Returns (key_id, raw_key).

    The raw key is returned only once — it is stored as a bcrypt hash.
    """
    raw_key = generate_api_key()
    key_id = str(uuid4())
    now = datetime.now(UTC).isoformat()
    expires_at = None
    if expires_days:
        expires_at = (datetime.now(UTC) + timedelta(days=expires_days)).isoformat()

    await db.execute(
        """
        INSERT INTO api_keys (id, name, key_hash, key_prefix, role, models,
                              rate_limit, created_at, expires_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            key_id,
            name,
            hash_api_key(raw_key),
            raw_key[:12],
            role,
            json.dumps(models or ["*"]),
            rate_limit,
            now,
            expires_at,
        ),
    )
    await db.commit()
    logger.info("Created API key '%s' (id=%s, role=%s)", name, key_id, role)
    return key_id, raw_key


async def authenticate_api_key(db: Database, raw_key: str) -> AuthUser | None:
    """Look up and verify an API key. Returns AuthUser or None."""
    rows = await db.fetchall("SELECT * FROM api_keys")
    for row in rows:
        if verify_api_key(raw_key, row["key_hash"]):
            # Check expiry
            if row["expires_at"]:
                expires = datetime.fromisoformat(row["expires_at"])
                if datetime.now(UTC) > expires:
                    logger.warning("Expired API key used: %s", row["name"])
                    return None

            # Update last_used_at
            await db.execute(
                "UPDATE api_keys SET last_used_at = ? WHERE id = ?",
                (datetime.now(UTC).isoformat(), row["id"]),
            )
            await db.commit()

            return AuthUser(
                user_id=row["name"],
                display_name=row["name"],
                roles=[row["role"]],
                allowed_models=json.loads(row["models"]),
                auth_method="api_key",
                key_id=row["id"],
                rate_limit=row["rate_limit"],
            )
    return None


# ---------------------------------------------------------------------------
# JWT issuance (for LDAP sessions)
# ---------------------------------------------------------------------------


def _get_jwt_secret() -> str:
    """Get the JWT signing secret."""
    settings = get_settings()
    secret = settings.security.jwt_secret
    if not secret:
        # In production, this should be set explicitly.
        # For development, generate a random secret (sessions won't survive restarts).
        logger.warning("No JWT secret configured — generating ephemeral secret")
        secret = secrets.token_urlsafe(64)
        settings.security.jwt_secret = secret
    return secret


def issue_jwt(
    user_id: str, display_name: str, roles: list[str], models: list[str]
) -> tuple[str, str, datetime]:
    """Issue a JWT session token.

    Returns (token, jti, expires_at).
    """
    settings = get_settings()
    now = datetime.now(UTC)
    jti = str(uuid4())
    expires_at = now + timedelta(hours=settings.security.jwt_expiry_hours)
    payload = {
        "sub": user_id,
        "name": display_name,
        "roles": roles,
        "models": models,
        "jti": jti,
        "iat": now,
        "exp": expires_at,
        "iss": "lean-ai-serve",
    }
    token = jwt.encode(payload, _get_jwt_secret(), algorithm="HS256")
    return token, jti, expires_at


def decode_jwt(token: str) -> dict | None:
    """Decode and validate a JWT. Returns payload dict or None."""
    try:
        return jwt.decode(
            token,
            _get_jwt_secret(),
            algorithms=["HS256"],
            issuer="lean-ai-serve",
        )
    except jwt.ExpiredSignatureError:
        logger.debug("JWT expired")
        return None
    except jwt.InvalidTokenError as e:
        logger.debug("Invalid JWT: %s", e)
        return None


# ---------------------------------------------------------------------------
# FastAPI dependency — authenticate any request
# ---------------------------------------------------------------------------


def get_db_from_request(request: Request) -> Database:
    """Extract the Database instance from app state."""
    return request.app.state.db


async def authenticate(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer_scheme),
) -> AuthUser:
    """Authenticate the request via API key, JWT, or OIDC token.

    Injected as a FastAPI dependency.
    """
    settings = get_settings()

    # No auth configured — allow anonymous
    if settings.security.mode == "none":
        return AuthUser(
            user_id="anonymous",
            display_name="Anonymous",
            roles=["admin"],
            allowed_models=["*"],
            auth_method="none",
        )

    if credentials is None:
        raise HTTPException(status_code=401, detail="Authorization header required")

    token = credentials.credentials
    db = get_db_from_request(request)
    modes = settings.security.mode.lower().split("+")

    # Try API key auth
    if "api_key" in modes and token.startswith(API_KEY_PREFIX):
        user = await authenticate_api_key(db, token)
        if user:
            return user
        raise HTTPException(status_code=401, detail="Invalid or expired API key")

    # Try JWT (LDAP-issued session token)
    if "ldap" in modes:
        payload = decode_jwt(token)
        if payload:
            # Check if token has been revoked
            jti = payload.get("jti")
            if jti and jti in _revoked_tokens:
                raise HTTPException(status_code=401, detail="Token has been revoked")
            return AuthUser(
                user_id=payload["sub"],
                display_name=payload.get("name", payload["sub"]),
                roles=payload.get("roles", ["user"]),
                allowed_models=payload.get("models", ["*"]),
                auth_method="ldap",
            )

    # Try OIDC
    if "oidc" in modes:
        oidc_validator = getattr(request.app.state, "oidc_validator", None)
        if oidc_validator is None:
            raise HTTPException(
                status_code=503, detail="OIDC validator not initialized"
            )
        user = await oidc_validator.validate_token(token)
        if user:
            return user
        raise HTTPException(status_code=401, detail="Invalid OIDC token")

    raise HTTPException(status_code=401, detail="Invalid credentials")


# ---------------------------------------------------------------------------
# Permission check dependency
# ---------------------------------------------------------------------------


def require_permission(permission: str):
    """FastAPI dependency that checks RBAC permissions."""
    from lean_ai_serve.security.rbac import check_permission

    async def _check(user: AuthUser = Depends(authenticate)) -> AuthUser:
        if not check_permission(user, permission):
            raise HTTPException(
                status_code=403,
                detail=f"Insufficient permissions: requires '{permission}'",
            )
        return user

    return _check
